# Generated by Django 4.1.7 on 2023-03-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
