# Generated by Django 4.1.7 on 2023-03-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_content_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='default_cover.wepb', upload_to=''),
        ),
    ]
